default: &default
  adapter: postgresql
  encoding: unicode
  database: mm_dev
  pool: 5
  timeout: 5000
  username: mm_dev
  password: mm_dev

development:
  <<: *default
  database: 

test:
  <<: *default

production:
  <<: *default
